# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kW93ZW0300Da9yz36Ws2eVLTD_qg5FQY
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# 
# # Title for the app
# st.title("Energy Management System (EMS)")
# 
# # Load the saved model
# model = joblib.load('linear_regression_model.pkl')
# 
# # Input fields for user data
# feature_1 = st.number_input("Enter value for Feature 1", value=0.0)
# feature_2 = st.number_input("Enter value for Feature 2", value=0.0)
# feature_3 = st.number_input("Enter value for Feature 3", value=0.0)
# feature_4 = st.number_input("Enter value for Feature 4", value=0.0)
# 
# # Load CSV data if needed (optional, e.g., for data display)
# data = pd.read_csv('ElectricCarData_Clean.csv')
# st.write("Dataset Preview:")
# st.dataframe(data.head())
# 
# # Button to make predictions
# if st.button('Predict Energy Usage'):
#     # Prepare input for the model
#     input_features = np.array([[feature_1, feature_2, feature_3, feature_4]])
# 
#     # Make prediction
#     prediction = model.predict(input_features)
# 
#     # Display prediction
#     st.write(f"Predicted Energy Usage: {prediction[0]:.2f} kWh")

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# 
# # Title for the app
# st.title("Energy Management System (EMS)")
# 
# # Load the saved model
# model = joblib.load('linear_regression_model.pkl')
# 
# # Input fields for user data
# feature_1 = st.number_input("Enter value for Feature 1", value=0.0)
# feature_2 = st.number_input("Enter value for Feature 2", value=0.0)
# feature_3 = st.number_input("Enter value for Feature 3", value=0.0)
# feature_4 = st.number_input("Enter value for Feature 4", value=0.0)
# 
# # Load any necessary CSV data
# data = pd.read_csv('ElectricCarData_Clean.csv')  # Make sure to replace this with your actual data file
# st.write("Dataset Preview:")
# st.dataframe(data.head())
# 
# # Button to make predictions
# if st.button('Predict Energy Usage'):
#     input_features = np.array([[feature_1, feature_2, feature_3, feature_4,0,0,0]])
#     prediction = model.predict(input_features)
#     st.write(f"Predicted Energy Usage: {prediction[0]:.2f} kWh")
#

from pyngrok import ngrok

# Run the Streamlit app
!streamlit run app.py &

# Expose the app to the internet
public_url = ngrok.connect(port='8501')
print(f"App is running at: {public_url}")

ngrok.disconnect(public_url)
public_url = ngrok.connect(port='8501')
print(f"App is running at: {public_url}")